-- D1 (SQLite) schema — port of the retired Supabase schema (see supabase/schema.sql and
-- supabase/migrations/*.sql for the source of truth this was ported from). Run once via:
--   npx wrangler d1 execute gmp-closegap-db --remote --file=schema.sql
--
-- No RLS/security-definer equivalent exists in D1 — the Worker (src/*.js) is the ONLY
-- thing with a binding to this database; every permission rule enforced by Postgres RLS
-- or by gmp_save_record/gmp_report_traffic in supabase/schema.sql is re-implemented as
-- plain JS checks in the Worker before any statement here runs. Never expose this
-- database directly to the browser.

-- Replaces Supabase Auth + gmp_members. login_id is a Username OR a real email, Admin's
-- choice per account — no synthetic-email hack needed here (that only existed because
-- Supabase Auth required a real email shape; D1 has no such constraint).
create table if not exists users (
  id text primary key,                  -- uuid, generated by the Worker at creation
  login_id text not null,               -- as typed at login: Username or Email
  login_id_lower text not null,         -- lower(login_id), for case-insensitive uniqueness
  password_hash text not null,          -- base64, PBKDF2-SHA256 output
  password_salt text not null,          -- base64, random 16 bytes per account
  pbkdf2_iterations integer not null,   -- recorded per-account so the iteration count can
                                         -- be raised later without invalidating old hashes
  display_name text not null,
  role text not null check (role in ('admin','user')),
  disabled integer not null default 0,  -- 0/1 (SQLite has no boolean type)
  created_at text not null              -- ISO 8601 UTC
);
create unique index if not exists users_login_id_idx on users(login_id_lower);

-- Port of gmp_records. record_key is computed and stored by the Worker (kind||':'||id)
-- rather than relying on a SQLite generated column, to avoid depending on the exact
-- SQLite feature-version D1 runs.
create table if not exists gmp_records (
  kind text not null check (kind in ('finding','settings')),
  id text not null check (id glob '[A-Za-z0-9_-]*' and length(id) between 1 and 100),
  record_key text not null unique,
  data text not null,                   -- JSON, stored as TEXT (no jsonb in SQLite)
  revision integer not null default 1,
  deleted integer not null default 0,
  updated_at text not null,             -- ISO 8601 UTC, string-sortable like Postgres timestamptz
  primary key (kind, id)
);
create index if not exists gmp_records_updated_at_idx on gmp_records(updated_at);

-- Port of gmp_audit. Server-written only (see src/records.js / src/admin.js) — the
-- browser never sends actor identity, matching "server audit is authoritative".
create table if not exists gmp_audit (
  id integer primary key autoincrement,
  ts text not null,                     -- ISO 8601 UTC
  actor_id text not null,
  actor_name text not null,
  device text not null,
  action text not null,
  detail text not null,
  area text not null
);
create index if not exists gmp_audit_ts_idx on gmp_audit(ts desc);

-- Port of gmp_traffic_daily. Each device reports its own cumulative today total (not a
-- delta); upsert keeps GREATEST(old,new) so retries/out-of-order calls never regress it.
create table if not exists gmp_traffic_daily (
  date text not null,                   -- 'YYYY-MM-DD'
  device text not null,
  bytes integer not null default 0,
  updated_at text not null,
  primary key (date, device)
);
create index if not exists gmp_traffic_daily_date_idx on gmp_traffic_daily(date);
